---
title: "Data observation"
author: "Chen Lee"
date: "2017/3/2"
output:
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Data observation

```{r, message=FALSE, warning=FALSE, echo=FALSE}
rm(list=ls()) 
library(ggplot2)
library(dplyr)
library(tidyr)
library(readxl)
#####################################################################
load("~/Dropbox/Data/ student ability.Rdata")

load("~/Dropbox/Data/registration.Rdata")
#載入啦啦隊名單
lala101<- read_excel("~/Dropbox/lala/lala101.xlsx")

regisdata2<-registration.data[,c('學號','10101中文姓名')]
colnames(regisdata2)<-c('ID','name')

mergeeco<-full_join(regisdata2,lala101,by='name')
eco101<-dplyr::filter(mergeeco,substring(mergeeco$ID,2,4)=="100")
lala.na.location<-which(is.na(eco101$lala)) #lala為NA的資料位置
eco101[lala.na.location,c('lala')]<-0
```

```{r}
#樣本個數觀察
table(eco101$lala)
```

```{r, message=FALSE, warning=FALSE}
#合併能力與平圴成績
eco101<-left_join(eco101,irt.out2,by='ID')

#  觀察到有些沒lala的人，沒念完，所以無能力與成績資料，有可能在準備轉學。

eco101$lala<-as.logical(eco101$lala)
```

觀察到有7位些沒lala的人，沒念完，所以無能力與成績資料，有可能在準備轉學。

In our sample, there are xxx students in lala, and yyyy not in lala.

First, we look at the gpa difference across two groups

```{r, message=FALSE, warning=FALSE}
# 圖： 平均成績與lala
eco101 %>% ggplot(aes(x=lala,y=cum.gpa))+
  geom_boxplot()+
  ggtitle('有無參加lala學生能力分佈')+
  theme(text = element_text(family = 'STSongti-TC-Light'))+
  xlab('lala')+
  ylab('平均成績')
```

Second graph is the difference based on extracted ability.

```{r, message=FALSE, warning=FALSE}
eco101 %>% ggplot(aes(x=lala,y=ab))+
  geom_boxplot()+
  ggtitle('有無參加lala學生能力分佈')+
  theme(text = element_text(family = 'STSongti-TC-Light'))+
  xlab('lala')+
  ylab('經濟專業能力')
```

參加啦啦成績離散度小，是因為變好朋友學習方法相近？

## 啦啦對於經原
是否參加啦啦經原比較會被當？不同學年入學學生的反應是否有明顯不同？



